-- 코드를 작성해주세요
SELECT ROUTE, CONCAT(CAST(ROUND(SUM(D_BETWEEN_DIST), 1) AS CHAR), 'km') AS TOTAL_DISTANCE, 
       CONCAT(CAST(ROUND(AVG(D_BETWEEN_DIST), 2) AS CHAR), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC