-- 코드를 작성해주세요
SELECT B.ID, C.FISH_NAME, A.LENGTH 
FROM (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE) AS A JOIN FISH_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH
      JOIN FISH_NAME_INFO AS C ON B.FISH_TYPE = C.FISH_TYPE
ORDER BY ID