-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/' ,FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS A JOIN USED_GOODS_FILE AS B ON A.BOARD_ID = B.BOARD_ID
WHERE A.VIEWS = (SELECT MAX(A.VIEWS) AS 'VIEWS' FROM USED_GOODS_BOARD AS A)
ORDER BY FILE_ID DESC